services:
  rest-calendar:
    build:
      context: .
    container_name: rest-calendar
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - redis

  redis:
    image: redis:8.2.2-alpine
    container_name: redis
    env_file:
      - .env
    volumes:
      - ./docker/redis-entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - redis-data:/data
    command: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped

volumes:
  redis-data: